crops:
  enabled:
    - wheat: true
    - carrots: true
    - potatoes: true
    - beetroots: true
    - nether_wart: true

effects:
  particles:
    enabled: true
    type: VILLAGER_HAPPY
    count: 10
  sound:
    enabled: true
    type: BLOCK_CROP_BREAK
    volume: 1.0
    pitch: 1.0

permissions:
  require_permission: false
  permission_node: harvester.use

messages:
  no_permission: "&cYou don't have permission to harvest here!"
  update_available: "&eA new version of Harvester is available!"

auto_updater:
  enabled: true
  notify_permission: harvester.update.notify

bstats:
  enabled: true